### ISSUE TITLE
Missing dependency: click_datetime

### ISSUE THREAD

**Issue by Netherdrake** [PBSA/python-peerplays#3]
```
~ % peerplays --help
Traceback (most recent call last):
  File "/home/tom/anaconda3/bin/peerplays", line 7, in <module>
    from peerplays.cli.cli import main
  File "/home/tom/anaconda3/lib/python3.6/site-packages/peerplays/cli/cli.py", line 38, in <module>
    from click_datetime import Datetime
ModuleNotFoundError: No module named 'click_datetime'
~ % pip install click_datetime
Collecting click_datetime
  Downloading click_datetime-0.2-py2.py3-none-any.whl
Requirement already satisfied: click in ./anaconda3/lib/python3.6/site-packages (from click_datetime)
Installing collected packages: click-datetime
Successfully installed click-datetime-0.2
```

**Comment by xeroc** [comment]
Thanks .. fixed
